// protoc -I . place.proto --go_out=plugins=grpc:.
// protoc -I . place.proto --grpc-gateway_out . --go_out=plugins=grpc:.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.8
// source: place.proto

package go_proto

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SectorId int64  `protobuf:"varint,2,opt,name=SectorId,proto3" json:"SectorId,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *PlaceRequest) Reset() {
	*x = PlaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceRequest) ProtoMessage() {}

func (x *PlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceRequest.ProtoReflect.Descriptor instead.
func (*PlaceRequest) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlaceRequest) GetSectorId() int64 {
	if x != nil {
		return x.SectorId
	}
	return 0
}

func (x *PlaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SectorId int64  `protobuf:"varint,2,opt,name=SectorId,proto3" json:"SectorId,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *PlaceResponse) Reset() {
	*x = PlaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceResponse) ProtoMessage() {}

func (x *PlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceResponse.ProtoReflect.Descriptor instead.
func (*PlaceResponse) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlaceResponse) GetSectorId() int64 {
	if x != nil {
		return x.SectorId
	}
	return 0
}

func (x *PlaceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type IdPlaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdPlaceRequest) Reset() {
	*x = IdPlaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdPlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdPlaceRequest) ProtoMessage() {}

func (x *IdPlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdPlaceRequest.ProtoReflect.Descriptor instead.
func (*IdPlaceRequest) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{2}
}

func (x *IdPlaceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IdPlaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdPlaceResponse) Reset() {
	*x = IdPlaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdPlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdPlaceResponse) ProtoMessage() {}

func (x *IdPlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdPlaceResponse.ProtoReflect.Descriptor instead.
func (*IdPlaceResponse) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{3}
}

func (x *IdPlaceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StatusPlaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StatusPlaceResponse) Reset() {
	*x = StatusPlaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusPlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusPlaceResponse) ProtoMessage() {}

func (x *StatusPlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusPlaceResponse.ProtoReflect.Descriptor instead.
func (*StatusPlaceResponse) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{4}
}

func (x *StatusPlaceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_place_proto protoreflect.FileDescriptor

var file_place_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x49, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x49, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xf1, 0x02, 0x0a, 0x0c, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x3a, 0x01, 0x2a,
	0x12, 0x5c, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12,
	0x15, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x2a, 0x12, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x58,
	0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x13, 0x2e,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x1a, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x53, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x0b, 0x5a,
	0x09, 0x2f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_place_proto_rawDescOnce sync.Once
	file_place_proto_rawDescData = file_place_proto_rawDesc
)

func file_place_proto_rawDescGZIP() []byte {
	file_place_proto_rawDescOnce.Do(func() {
		file_place_proto_rawDescData = protoimpl.X.CompressGZIP(file_place_proto_rawDescData)
	})
	return file_place_proto_rawDescData
}

var file_place_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_place_proto_goTypes = []interface{}{
	(*PlaceRequest)(nil),        // 0: place.PlaceRequest
	(*PlaceResponse)(nil),       // 1: place.PlaceResponse
	(*IdPlaceRequest)(nil),      // 2: place.IdPlaceRequest
	(*IdPlaceResponse)(nil),     // 3: place.IdPlaceResponse
	(*StatusPlaceResponse)(nil), // 4: place.StatusPlaceResponse
}
var file_place_proto_depIdxs = []int32{
	0, // 0: place.PlaceService.CreatePlace:input_type -> place.PlaceRequest
	2, // 1: place.PlaceService.DeletePlace:input_type -> place.IdPlaceRequest
	0, // 2: place.PlaceService.UpdatePlace:input_type -> place.PlaceRequest
	2, // 3: place.PlaceService.GetPlace:input_type -> place.IdPlaceRequest
	3, // 4: place.PlaceService.CreatePlace:output_type -> place.IdPlaceResponse
	4, // 5: place.PlaceService.DeletePlace:output_type -> place.StatusPlaceResponse
	4, // 6: place.PlaceService.UpdatePlace:output_type -> place.StatusPlaceResponse
	1, // 7: place.PlaceService.GetPlace:output_type -> place.PlaceResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_place_proto_init() }
func file_place_proto_init() {
	if File_place_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_place_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdPlaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdPlaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusPlaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_place_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_place_proto_goTypes,
		DependencyIndexes: file_place_proto_depIdxs,
		MessageInfos:      file_place_proto_msgTypes,
	}.Build()
	File_place_proto = out.File
	file_place_proto_rawDesc = nil
	file_place_proto_goTypes = nil
	file_place_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlaceServiceClient is the client API for PlaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaceServiceClient interface {
	CreatePlace(ctx context.Context, in *PlaceRequest, opts ...grpc.CallOption) (*IdPlaceResponse, error)
	DeletePlace(ctx context.Context, in *IdPlaceRequest, opts ...grpc.CallOption) (*StatusPlaceResponse, error)
	UpdatePlace(ctx context.Context, in *PlaceRequest, opts ...grpc.CallOption) (*StatusPlaceResponse, error)
	GetPlace(ctx context.Context, in *IdPlaceRequest, opts ...grpc.CallOption) (*PlaceResponse, error)
}

type placeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaceServiceClient(cc grpc.ClientConnInterface) PlaceServiceClient {
	return &placeServiceClient{cc}
}

func (c *placeServiceClient) CreatePlace(ctx context.Context, in *PlaceRequest, opts ...grpc.CallOption) (*IdPlaceResponse, error) {
	out := new(IdPlaceResponse)
	err := c.cc.Invoke(ctx, "/place.PlaceService/CreatePlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placeServiceClient) DeletePlace(ctx context.Context, in *IdPlaceRequest, opts ...grpc.CallOption) (*StatusPlaceResponse, error) {
	out := new(StatusPlaceResponse)
	err := c.cc.Invoke(ctx, "/place.PlaceService/DeletePlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placeServiceClient) UpdatePlace(ctx context.Context, in *PlaceRequest, opts ...grpc.CallOption) (*StatusPlaceResponse, error) {
	out := new(StatusPlaceResponse)
	err := c.cc.Invoke(ctx, "/place.PlaceService/UpdatePlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placeServiceClient) GetPlace(ctx context.Context, in *IdPlaceRequest, opts ...grpc.CallOption) (*PlaceResponse, error) {
	out := new(PlaceResponse)
	err := c.cc.Invoke(ctx, "/place.PlaceService/GetPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaceServiceServer is the server API for PlaceService service.
type PlaceServiceServer interface {
	CreatePlace(context.Context, *PlaceRequest) (*IdPlaceResponse, error)
	DeletePlace(context.Context, *IdPlaceRequest) (*StatusPlaceResponse, error)
	UpdatePlace(context.Context, *PlaceRequest) (*StatusPlaceResponse, error)
	GetPlace(context.Context, *IdPlaceRequest) (*PlaceResponse, error)
}

// UnimplementedPlaceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlaceServiceServer struct {
}

func (*UnimplementedPlaceServiceServer) CreatePlace(context.Context, *PlaceRequest) (*IdPlaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlace not implemented")
}
func (*UnimplementedPlaceServiceServer) DeletePlace(context.Context, *IdPlaceRequest) (*StatusPlaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlace not implemented")
}
func (*UnimplementedPlaceServiceServer) UpdatePlace(context.Context, *PlaceRequest) (*StatusPlaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlace not implemented")
}
func (*UnimplementedPlaceServiceServer) GetPlace(context.Context, *IdPlaceRequest) (*PlaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlace not implemented")
}

func RegisterPlaceServiceServer(s *grpc.Server, srv PlaceServiceServer) {
	s.RegisterService(&_PlaceService_serviceDesc, srv)
}

func _PlaceService_CreatePlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceServiceServer).CreatePlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceService/CreatePlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceServiceServer).CreatePlace(ctx, req.(*PlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaceService_DeletePlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdPlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceServiceServer).DeletePlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceService/DeletePlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceServiceServer).DeletePlace(ctx, req.(*IdPlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaceService_UpdatePlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceServiceServer).UpdatePlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceService/UpdatePlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceServiceServer).UpdatePlace(ctx, req.(*PlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaceService_GetPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdPlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceServiceServer).GetPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceService/GetPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceServiceServer).GetPlace(ctx, req.(*IdPlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlaceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "place.PlaceService",
	HandlerType: (*PlaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlace",
			Handler:    _PlaceService_CreatePlace_Handler,
		},
		{
			MethodName: "DeletePlace",
			Handler:    _PlaceService_DeletePlace_Handler,
		},
		{
			MethodName: "UpdatePlace",
			Handler:    _PlaceService_UpdatePlace_Handler,
		},
		{
			MethodName: "GetPlace",
			Handler:    _PlaceService_GetPlace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "place.proto",
}
